# header is not currently used.
# std_msgs/Header header

# The name of the base link
string base_frame

# The name of the end effector link
string end_effector_frame

# The robot name in the Jrl package (see https://github.com/jstmn/jrl). Needs to match whatever the configured value is, which is set by a CppFlowEnvironentConfig message
string jrl_robot_name

# Array of planning problems. CppFlow will solve all of them in parallel.
CppFlowProblem[] problems

# Optionally specify the initial joint configuration. Note that only the positional element of the configuration will be used - the velocity and effort elements will be ignored
bool initial_configuration_is_set
sensor_msgs/JointState initial_configuration

# Specify the maximum allowed planning time
float64 max_planning_time_sec

# Specify whether to plan with anytime mode or now. When enabled, the planner will continue optimizing until max_planning_time_sec seconds have elapsed or no more progress is detected. If disabled, the first valid plan will be returned.
bool anytime_mode_enabled 

# Specify the maximum allowed reference path tracking and smoothness error. See "CppFlow: Generative Inverse Kinematics for Efficient and Robust Cartesian Path Planning" for a description of mjac
float64 max_allowed_position_error_cm
float64 max_allowed_rotation_error_deg
float64 max_allowed_mjac_deg
float64 max_allowed_mjac_cm

# Verbosity. 0: No output, 1: Info, 2. Debug, 3. Extreme debug
int32 verbosity

---

trajectory_msgs/JointTrajectory[] trajectories
bool[] success
string[] errors

bool is_malformed_query
string malformed_query_error